import Head from 'next/head'
import Nav from '../components/Nav/Nav'
import styles from '../styles/Main.module.css';



export default function Home() {
  return (
    <div>
      <Head>
        <title>Visit Japan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <main>
        <Nav/>
        <section>
          {/* <h3 className={styles.favorite_spots_title}>FAVORITE SPOTS</h3> */}
          <br/>
          <div className={styles.spots}>
              <div><h3></h3></div>
              <div><h3></h3></div>
              <div><h3></h3></div>
          </div>
        </section>
    </main>  
      
    </div>
  )
}
